pipelines:
  custom:
    nightly-humble-build:
      - step:
          image: osrf/ros:humble-desktop
          name: 'checkout BRASH workspace'
          script:
            - apt update
            - export DEBIAN_FRONTEND=noninteractive
            - apt -y install git python3-pip python3-rosdep python3-wstool python3-colcon*
            - apt -y upgrade
            - pip3 install vcstool
            - source /opt/ros/humble/setup.bash
            - rosdep update
            - mkdir src
            - vcs import src < brash.repos
            - rosdep install --from-paths src -y --ignore-src
          artifacts:
            - src/**
      - step:
          image: osrf/ros:humble-desktop
          name: 'build workspace'
          script:
            - source /opt/ros/humble/setup.bash  
            - colcon build
          artifacts:
            - build/**
            - log/**
            - install/**
      - step:
          image: osrf/ros:humble-desktop
          name: 'run colcon tests'
          script:
            - source /opt/ros/humble/setup.bash  
            - . install/local_setup.bash
            - colcon test  --event-handlers console_cohesion+ --ctest-args " -VVV" --return-code-on-test-failure

    test-cfe-build:
      - step:
          image: osrf/ros:humble-desktop
          name: 'cFS pull test'
          script:
            - git clone git@github.com:traclabs/cFS.git
            - pushd cFS
            - git submodule update --init --recursive
            # - cp cfe/cmake/Makefile.sample Makefile
            # - cp -r cfe/cmake/sample_defs sample_defs
            - ./submodule_status.sh
            - make SIMULATION=native prep
            - make
            - make install
            - popd
            - cd cFS/build/exe/cpu1
            - ./core-cpu1 | tee ../../../cFS_startup_cpu1.txt &
            - sleep 30 
            - ../host/cmdUtil --endian=LE --pktid=0x1806 --cmdcode=2 --half=0x0002

    full-brash-cfe-build:
      - step:
          image: osrf/ros:humble-desktop
          name: 'checkout BRASH workspace'
          script:
            - apt update
            - export DEBIAN_FRONTEND=noninteractive
            - apt -y install git python3-pip python3-rosdep python3-wstool python3-colcon*
            - apt -y upgrade
            - pip3 install vcstool
            - source /opt/ros/humble/setup.bash
            - rosdep update
            - mkdir src
            - vcs import src < brash.repos
            - rosdep install --from-paths src -y --ignore-src
          artifacts:
            - src/**
      - step:
          image: osrf/ros:humble-desktop
          name: 'build ROS packages'
          script:
            - source /opt/ros/humble/setup.bash
            - cd src/cfe_sbn_bridge_plugin
            - git checkout feature/launch-test-standup
            - cd ../..
            - colcon build --symlink-install
          artifacts:
            - build/**
            - log/**
            - install/**
            - src/**
      - step:
          image: osrf/ros:humble-desktop
          name: 'checkout cFS'
          script:
            - git clone git@github.com:traclabs/cFS.git
            - pushd cFS
            - git checkout submodule-cleanup
            - git submodule init
            - git submodule update
            # - git checkout main
            - cp cfe/cmake/Makefile.sample Makefile
            - cp -r cfe/cmake/sample_defs sample_defs
            - make SIMULATION=native prep
            - make
            - make install
            - popd
          artifacts:
            - build/**
            - log/**
            - install/**
            - src/**
            - cFS/**
      - step:
          image: osrf/ros:humble-desktop
          name: 'run colcon tests'
          script:
            - export CFE_ROOT=$(pwd)/cFS
            - source /opt/ros/humble/setup.bash  
            - . install/local_setup.bash
            - touch cFS/COLCON_IGNORE
            - colcon test  --event-handlers console_cohesion+ --ctest-args " -VVV" --return-code-on-test-failure
